DROP TABLE IF EXISTS PATIENT;
DROP TABLE IF EXISTS SAMPLE;

CREATE TABLE PATIENT (
  id INT AUTO_INCREMENT(0,1) PRIMARY KEY,
  PATIENT_ID VARCHAR(255),
  SEX VARCHAR(255),
  VITAL_STATUS VARCHAR(255),
  SMOKING_HISTORY VARCHAR(255),
  OS_MONTHS VARCHAR(255),
  OS_STATUS VARCHAR(255));

CREATE TABLE SAMPLE (
  id INT AUTO_INCREMENT(0,1) PRIMARY KEY,
  PATIENT_ID VARCHAR(255),
  PATIENT_IDX INT,
  SAMPLE_ID VARCHAR(255),
  SAMPLE_COLLECTION_SOURCE VARCHAR(255),
  SPECIMEN_PRESERVATION_TYPE VARCHAR(255),
  SPECIMEN_TYPE VARCHAR(255),
  DNA_INPUT VARCHAR(255),
  SAMPLE_COVERAGE VARCHAR(255),
  TUMOR_PURITY VARCHAR(255),
  MATCHED_STATUS VARCHAR(255),
  SAMPLE_TYPE VARCHAR(255),
  PRIMARY_SITE VARCHAR(255),
  METASTATIC_SITE VARCHAR(255),
  SAMPLE_CLASS VARCHAR(255),
  ONCOTREE_CODE VARCHAR(255),
  CANCER_TYPE VARCHAR(255),
  CANCER_TYPE_DETAILED VARCHAR(255));

INSERT INTO PATIENT (PATIENT_ID,SEX,VITAL_STATUS,SMOKING_HISTORY,OS_MONTHS,OS_STATUS)
  SELECT * from CSVREAD('data/data_clinical_patient.txt', null,'fieldSeparator=' || CHAR(9));

ALTER TABLE SAMPLE ADD FOREIGN KEY (PATIENT_IDX) REFERENCES PATIENT(ID);

INSERT INTO SAMPLE (PATIENT_ID,SAMPLE_ID,SAMPLE_COLLECTION_SOURCE,SPECIMEN_PRESERVATION_TYPE,SPECIMEN_TYPE,DNA_INPUT,SAMPLE_COVERAGE,TUMOR_PURITY,MATCHED_STATUS,SAMPLE_TYPE,PRIMARY_SITE,METASTATIC_SITE,SAMPLE_CLASS,ONCOTREE_CODE,CANCER_TYPE,CANCER_TYPE_DETAILED)
  SELECT * from CSVREAD('data/data_clinical_sample.txt', null, 'fieldSeparator=' || CHAR(9));

UPDATE SAMPLE
SET PATIENT_IDX = (SELECT ID FROM PATIENT p WHERE p.PATIENT_ID=SAMPLE.PATIENT_ID);
