DROP TABLE IF EXISTS PATIENT;
DROP TABLE IF EXISTS SAMPLE;

CREATE TABLE PATIENT
 as SELECT * from CSVREAD('data/data_clinical_patient.txt',
 'PATIENT_ID	SEX	VITAL_STATUS	SMOKING_HISTORY	OS_MONTHS	OS_STATUS', 'fieldSeparator=' || CHAR(9));

DELETE FROM PATIENT
  WHERE PATIENT_ID = 'PATIENT_ID';
ALTER TABLE PATIENT
  ADD id INT AUTO_INCREMENT(0,1) PRIMARY KEY;

CREATE TABLE SAMPLE
 as SELECT * from CSVREAD('data/data_clinical_sample.txt',
  'PATIENT_ID	SAMPLE_ID	SAMPLE_COLLECTION_SOURCE	SPECIMEN_PRESERVATION_TYPE	SPECIMEN_TYPE	DNA_INPUT	SAMPLE_COVERAGE	TUMOR_PURITY	MATCHED_STATUS	SAMPLE_TYPE	PRIMARY_SITE	METASTATIC_SITE	SAMPLE_CLASS	ONCOTREE_CODE	CANCER_TYPE	CANCER_TYPE_DETAILED',
  'fieldSeparator=' || CHAR(9));

DELETE FROM SAMPLE
  WHERE PATIENT_ID = 'PATIENT_ID';
ALTER TABLE SAMPLE
  ADD id INT AUTO_INCREMENT(0,1) PRIMARY KEY;